apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        args: ["--replSet", "rs0", "--bind_ip_all"]
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        emptyDir: {} # No Minikube, isso cria um volume temporário.
                     # Use PersistentVolumeClaim para persistência real em produção.
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: infra
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017